import LegalDocument from '../components/LegalDocument'

const TERMS_CONTENT = `**CHIRON**

TERMS OF USE

www.chironevo.com

Effective date: 21/09/2026

*These Terms govern the use of Chiron. Part B concerns what happens when
you publish something here and what the confidentiality agreement
between users does and does not do. It should be read before you publish
anything.*

**Part A | The Platform and the parties**

**1. THE OPERATOR**

1.1 The website www.chironevo.com (the "Platform") is operated by
Evangelos A. Koumasopoulos (the "Operator", "we", "us").

1.2 Registered address: 80 Panormou Street, 11523, Athens, Greece

Company or tax registration number: 069811425

Contact for all matters, including legal notices: legal@chironevo.com

1.3 These particulars are given in accordance with Article 4 of
Presidential Decree 131/2003, which transposes Directive 2000/31/EC on
electronic commerce into Greek law.

1.4 The Operator charges no registration fee, takes no commission, holds
no funds and receives no share of anything users agree between
themselves. If that changes, these Terms will be amended in accordance
with clause 27.

**2. WHAT THE PLATFORM IS**

2.1 The Platform is a listings board with a two-tier structure.
Registered users may publish descriptions of:

> • scientific ideas, inventions, research findings or research
> proposals which the user cannot develop alone, whether for lack of
> capital, equipment or laboratory facilities;
>
> • the capabilities of a laboratory or research unit seeking others
> with complementary capabilities;
>
> • creative material, including literary texts, song lyrics, screenplay
> outlines and film or story concepts.

2.2 Each listing has a public part, visible to registered users, and a
private part, which the person who published it may keep closed. Access
to the private part is granted only after the person requesting it has
accepted the confidentiality agreement described in clause 9 (the
"Confidentiality Agreement") and, where the Platform so provides, the
person who published the listing has approved the request.

2.3 The Platform additionally provides a messaging channel, a facility
for making and responding to offers, a record of accepted exchanges, a
facility for reporting content and users, and a facility for users to
review one another.

2.4 What a user receives in return for an idea or a work is entirely a
matter for the users concerned. It may be a sum of money. It may equally
be a place on a research team, an authorship or naming credit, access to
equipment, or anything else those users agree.

**3. WHAT THE PLATFORM IS NOT**

3.1 The Platform is not a register, a repository, a certification
service or a rights-recording service. Publishing something here creates
no right and secures no right.

3.2 The Platform is not a party to the confidentiality agreement
described in clause 9, nor to any agreement between users, and enforces
neither.

3.3 The record described in clause 11 is not a contract, a deed, an
assignment or an instrument of transfer, and it does not by itself
transfer any right.

3.4 The Platform is not an escrow, payment or settlement service, and no
payment is made through it.

3.5 The Platform is not a legal, patent, scientific, medical or
investment advisory service. Nothing on it may be relied upon for the
diagnosis, treatment or care of any person, nor as advice of any kind,
and it is not a channel for clinical or medical communication.

**4. ACCEPTANCE AND ELIGIBILITY**

4.1 These Terms of Use (the "Terms") form a binding agreement between
you and the Operator.

4.2 You accept them by ticking the relevant box when you register.
Acceptance requires a deliberate act. Browsing the Platform, scrolling a
page or closing a notice does not amount to acceptance.

4.3 The Operator records which version of these Terms you accepted,
together with the date and time of acceptance.

4.4 You must be at least 18 years old to register. The Platform is not
directed at minors and no account may be opened by or on behalf of a
minor.

4.5 If you do not accept these Terms, do not register and do not use the
Platform.

**5. AUTOMATED RANKING AND ARTIFICIAL INTELLIGENCE**

5.1 Parts of the Platform were built with the assistance of artificial
intelligence tools. This does not affect your rights or obligations
under these Terms.

5.2 No system on the Platform holds a conversation with you in place of
a human being, and no text shown to you is generated by such a system.
Decisions to remove content, to decide a report or to suspend an account
are taken by a person.

5.3 The Platform does rank listings automatically. When you open the
home page, it compares the listings you have published, the categories
and keywords in them, and the kind of exchange you say you are looking
for, with the listings published by other users. Each listing is given a
score, listings scoring below a threshold are left out, and the ten
highest are shown to you in order.

5.4 The main parameters of that ranking are: how closely the keywords in
a listing match the keywords in yours; whether the category of a listing
differs from your own, since the purpose is to bring together people
with complementary rather than identical capabilities; whether what
another user is asking for corresponds to what you appear able to offer;
and whether the kind of exchange sought matches the kind you have said
you want.

5.5 The ranking follows fixed rules written by a person. It is not a
learning system, it does not adapt on its own, and it produces no
assessment of you as a person. It uses only what you have published on
the Platform and what you have told us you are looking for. It does not
use your browsing behaviour and it does not use data obtained from
outside the Platform.

5.6 The ranking decides the order in which listings appear on the home
page and nothing else. It gives no one access to anything, it takes no
decision about you or your account, and it does not limit what you may
do on the Platform. You may disregard it and use the search bar, which
returns results without this ranking. How to object to the ranking is
explained in the Privacy Policy.

**Part B | Publication, confidentiality and records**

**6. THE PUBLIC PART OF A LISTING**

6.1 Anything you place in the public part of a listing can be read,
copied, recorded, photographed, forwarded and used by any registered
user. The Operator has no technical means of preventing that and gives
no undertaking to attempt it.

6.2 Publication cannot be undone. Removing a listing, or closing your
account, stops it being displayed. It does not recall what others have
already read, copied or acted upon.

6.3 Place in the public part only what you can afford to have known.

**7. IDEAS AS SUCH ARE NOT PROTECTED**

7.1 Copyright protects the particular expression of an idea, not the
idea, method, concept or discovery which that expression conveys
(Article 2(3) of Law 2121/1993). The wording of your listing may attract
copyright. What that wording describes does not.

7.2 Disclosure to the public destroys patentability. An invention can be
patented only if it is new, and it is not new if it already belongs to
the state of the art, which comprises everything made available to the
public anywhere in the world, in writing, orally or in any other way,
before the filing or priority date (Article 5(3) of Law 1733/1987;
Article 54 of the European Patent Convention).

7.3 Information is protected as a trade secret only for as long as it
remains secret (Articles 22A to 22K of Law 1733/1987, inserted by
Article 1 of Law 4605/2019, transposing Directive (EU) 2016/943).

7.4 Placing a description of an invention in the public part of a
listing is a disclosure to the public. It may permanently prevent you,
and anyone you later work with, from obtaining a patent for it anywhere.

**8. HOW TO USE THE TWO TIERS**

8.1 A disclosure made to a defined person who is under an obligation of
confidence is not, in principle, a disclosure to the public, and does
not of itself destroy novelty or end trade secret protection. The
private part of a listing, released only against the confidentiality
agreement in clause 9, is designed to work that way.

8.2 That protection depends entirely on the obligation of confidence
being effective and being observed. It is not a guarantee. If the person
who receives your private information discloses it, the information may
become part of the state of the art, and your remedy is a claim against
that person, not against the Operator.

8.3 The Operator therefore advises every user to:

> • obtain patent or other protection before publishing anything
> patentable, wherever that is realistic;
>
> • keep in the public part only what is needed to attract interest, and
> keep every operative detail in the private part;
>
> • release the private part only to persons you have reason to trust,
> and only to as many as you need;
>
> • consider a separate, individually negotiated written agreement for
> anything of substantial value, rather than relying on the standard
> Confidentiality Agreement in clause 9;
>
> • take independent legal advice before disclosing anything of value.

**9. THE CONFIDENTIALITY AGREEMENT BETWEEN USERS**

9.1 Before the private part of a listing is released, the person
requesting access must accept the Confidentiality Agreement with the
person who published that listing. The Operator makes that agreement
available in a standard form, and records its acceptance together with
the full name of each of the two users, the listing concerned and the
date and time.

9.2 That agreement is concluded between those two users alone. The
Operator is not a party to it, gives no warranty as to its
enforceability in any particular jurisdiction or against any particular
person, and takes no part in enforcing it. Supplying the standard form
is a convenience and is not legal advice to either user.

9.3 The Operator does not monitor whether users observe that agreement
and has no means of doing so. A breach of it is a matter between the
users concerned.

9.4 Users remain free to conclude a separate written agreement on
different terms. Where they do, that agreement governs the relationship
between them, and the Operator is no more a party to it than to the
standard one.

9.5 The Operator will, on request and where lawful, provide a user with
the record it holds of an acceptance under clause 9.1, for use in
proceedings between those users.

**10. THE DATE SHOWN ON A LISTING**

10.1 The Platform records the date and time at which each listing is
published and displays that date on the listing.

10.2 That record shows only that particular content was present on the
Platform on a particular date. It is not a registration, a deposit, a
certification, or proof of ownership, authorship, priority or invention,
and it creates no right of any kind. It carries whatever evidential
weight a court may choose to give it, and no more.

**11. THE RECORD OF AN EXCHANGE**

11.1 Where two users record on the Platform that they have reached
agreement, the Platform generates a record of that fact, showing the
users concerned, the listing concerned and the date and time.

11.2 That record is evidence of what those users entered on the
Platform. It is not a contract, and it does not itself transfer
ownership, copyright, patent rights or any other right.

11.3 Under Greek law, a transfer of economic rights in a copyright work,
and any licence to exploit such a work, is void unless made in writing
(Article 14 of Law 2121/1993). The transfer of a patent or a patent
application is likewise subject to the requirements of Article 12 of Law
1733/1987. An entry on the Platform does not satisfy those requirements.
Users who intend to transfer rights must conclude a separate written
agreement between themselves.

11.4 The Operator does not verify that what the record describes
actually happened, that either user performed, or that any right passed.

**12. RIGHTS IN WHAT YOU PUBLISH**

12.1 You keep every right you have in what you publish. The Operator
claims no ownership of it.

12.2 You grant the Operator a non-exclusive, royalty-free, worldwide
licence to store, reproduce and display your content on the Platform, to
the extent necessary to operate it and make your listing visible to the
users entitled to see it.

12.3 That licence is confined to that purpose. The Operator will not
exploit your content commercially, will not sub-license it and will not
use it for any other purpose.

12.4 The licence ends when the content ceases to be displayed, except
that it continues for so long as, and to the extent that, the Operator
keeps the content or the records described in clause 26, and for routine
backup copies which are overwritten in the ordinary course.

**Part C | Your obligations**

**13. WHAT YOU CONFIRM WHEN YOU PUBLISH**

13.1 By publishing, you confirm that:

> • the information in your profile is accurate and you are the person
> you say you are;
>
> • you own, or are otherwise entitled to disclose and to dispose of,
> everything you publish;
>
> • what you publish infringes no right of any third party;
>
> • you are not bound by any confidentiality obligation, employment
> term, institutional policy, funding condition or contract that
> prohibits you from disclosing it.

13.2 The last of those deserves particular attention. Employees,
doctoral candidates, hospital staff and researchers working under a
grant frequently do not own their results and are frequently prohibited
from publishing them. The Operator cannot know this and will not
investigate it. Checking your own position is your responsibility, and
it should be done before you publish rather than afterwards.

13.3 You must keep your credentials confidential, must not share your
account, and must tell the Operator without delay if you believe your
account has been used without your authority.

**14. CONTENT THAT MAY NOT BE PUBLISHED**

14.1 You must not publish, in either part of a listing, in a message, in
a review, or anywhere else on the Platform:

> • content infringing any patent, trade mark, copyright, trade secret
> or other right of a third party;
>
> • work which is not yours, presented as though it were;
>
> • personal data of any third party, and in particular any information
> concerning the health of an identified or identifiable person,
> including patient records, clinical images, laboratory results,
> genetic data and case histories, whether or not you have attempted to
> anonymise them;
>
> • unpublished results, data or materials belonging to an employer,
> university, hospital, research institution or funding body, without
> documented authorisation;
>
> • information received in confidence from any person;
>
> • content that is unlawful, defamatory, discriminatory or abusive, or
> that incites violence or hatred;
>
> • content promoting unlawful activity;
>
> • fictitious listings, spam, advertising unrelated to the purpose of
> the Platform, or content designed to deceive other users.

**15. LINKS AND EXTERNAL CONTENT**

15.1 The Platform is not designed to host or transmit material stored
elsewhere. You must not use a hyperlink, a file-sharing address, a QR
code or any comparable device in order to:

> • place before another user material which, if published on the
> Platform, would breach clause 14;
>
> • release the private part of a listing, or information obtained from
> it, outside the Platform;
>
> • avoid the Confidentiality Agreement in clause 9 or the access
> approval that precedes it.

15.2 The Operator does not review, endorse or control any material
reached through a link, and is not responsible for it. Following a link
takes you outside the Platform and outside these Terms.

15.3 Placing a link is at your own risk and at the risk of the person
who follows it. Where a link is used to circumvent clause 9, the person
who placed it is in breach both of these Terms and of the
Confidentiality Agreement, and the Operator may act under clause 21.

**16. CONDUCT**

16.1 You must not harass, threaten or abuse any user, whether in
messages, in reviews or in listing content.

16.2 You must not operate more than one account, nor use an account to
negotiate with yourself, to influence a review or to affect the standing
of any user.

16.3 You must not extract data from the Platform by automated means, nor
attempt to circumvent its technical restrictions.

16.4 Reviews you publish must relate to a dealing that actually took
place and must be honest.

**Part D | The position of the Operator**

**17. NOT A PARTY TO ANY ARRANGEMENT**

17.1 The Operator is a neutral intermediary. The Operator is not a party
to, and owes no obligation under, any agreement, sale, assignment,
licence, collaboration, Confidentiality Agreement or other arrangement
concluded between users, whether concluded through the Platform or
elsewhere.

17.2 The Operator does not:

> • verify the identity, qualifications, affiliation or good faith of
> any user;
>
> • verify the accuracy, originality, feasibility or value of any
> listing;
>
> • verify that a user owns, or is entitled to dispose of, what that
> user publishes;
>
> • introduce, endorse, recommend, rank or select counterparties;
>
> • negotiate, draft, review or witness any agreement between users;
>
> • hold, transmit, escrow, process or guarantee any payment;
>
> • mediate, arbitrate or otherwise take any part in a dispute between
> users;
>
> • supervise or enforce performance of anything users agree, including
> the Confidentiality Agreement in clause 9.

17.3 Users are solely responsible for satisfying themselves as to the
identity and reliability of anyone they deal with, for the terms on
which they deal, and for taking their own legal, patent, tax and
technical advice before doing so.

**18. NEGOTIATIONS AND DEALINGS OUTSIDE THE PLATFORM**

18.1 The Platform may set a period within which an offer may be answered
before it lapses. That period is a technical convenience which prevents
listings being held indefinitely. It creates no obligation to answer, no
obligation to negotiate in good faith, and no contract if it expires.

18.2 Either user may withdraw from a negotiation at any time and for any
reason. Withdrawal through the Platform has no consequence beyond ending
the exchange on the Platform, and the Operator takes no view on why it
happened.

18.3 Users are free to continue their dealings away from the Platform.
Where they do, the Platform holds no record of what was agreed, the
record described in clause 11 does not arise, and neither user can later
rely on the Platform for evidence of it.

18.4 The obligations of confidence a user has accepted under clause 9
are not affected by where the parties continue their discussions.

**19. STORAGE OF CONTENT AND ABSENCE OF MONITORING**

19.1 The Operator stores content at the request of the users who publish
it and neither selects nor modifies that content.

19.2 The Operator is accordingly not liable for content published by
users, provided that the Operator has no actual knowledge of unlawful
activity or content and, upon obtaining such knowledge, acts
expeditiously to remove it or to disable access to it (Article 6 of
Regulation (EU) 2022/2065).

19.3 The Operator is under no general obligation to monitor the content
published on the Platform, nor actively to seek facts indicating
unlawful activity (Article 8 of Regulation (EU) 2022/2065).

**20. REPORTING UNLAWFUL CONTENT**

20.1 Any person, whether registered or not, may notify the Operator of
content on the Platform which that person considers unlawful, by email
to legal@chironevo.com or through the reporting facility on the
Platform.

20.2 So that the Operator can act on it, a notice should contain:

> • a sufficiently substantiated explanation of why the content is
> considered unlawful;
>
> • the exact location of the content, in particular the address of the
> listing concerned;
>
> • the name and an email address of the person submitting the notice,
> except where the notice concerns an offence referred to in Articles 3
> to 7 of Directive 2011/93/EU;
>
> • a statement confirming the good faith belief of that person that the
> information in the notice is accurate and complete.

20.3 The Operator will confirm receipt without undue delay and will
decide on the notice in a timely, diligent, non-arbitrary and objective
manner, informing the person who submitted it of the outcome.

**21. REMOVAL OF CONTENT AND SUSPENSION OF ACCOUNTS**

21.1 The Operator may remove a listing, disable access to content, or
suspend or terminate an account where these Terms have been breached. A
suspension is imposed without a fixed end date and may be lifted at any
time.

21.2 The Operator will give the affected user a statement of reasons
which sets out:

> • what was removed or restricted, and for how long;
>
> • the facts and circumstances relied upon in reaching the decision;
>
> • the ground in these Terms, or the legal ground, on which the
> decision rests;
>
> • whether automated means were used in reaching it;
>
> • how the decision may be contested.

21.3 The Operator need not disclose the identity of a person who
submitted a report, nor material whose disclosure would prejudice the
safety of any person, the prevention of crime, or an ongoing
investigation.

21.4 A user affected by such a decision may contest it by email to
legal@chironevo.com within six months of being notified. The Operator
will reconsider the original evidence together with anything new the
user provides, and will reverse the decision where the complaint shows
that the content was neither unlawful nor in breach of these Terms.

21.5 For so long as the Operator does not exceed the thresholds of a
micro enterprise within the meaning of Recommendation 2003/361/EC, the
additional obligations laid down in Section 3 of Chapter III of
Regulation (EU) 2022/2065 do not apply to it. The review in clause 21.4
is offered voluntarily.

21.6 Suspension of an account does not delete anything. Content and
records relating to a suspended account are retained as described in
clause 24 and in the Privacy Policy.

21.7 Where the Operator becomes aware of information giving rise to a
suspicion that a criminal offence involving a threat to the life or
safety of a person has taken place, is taking place or is likely to take
place, the Operator will inform the competent authorities (Article 18 of
Regulation (EU) 2022/2065).

**22. AVAILABILITY OF THE PLATFORM**

22.1 The Platform is provided as it stands and as it is available,
without warranty of any kind.

22.2 The Operator does not warrant that the Platform will be available
without interruption or free from error, that content on it is accurate
or reliable, or that it will meet any particular requirement.

22.3 The Operator may modify, suspend or discontinue the Platform, in
whole or in part, at any time. If the Platform is to close permanently,
registered users will be given at least thirty days notice by email so
that they may retrieve their content and the records of the
Confidentiality Agreements they have accepted or been given, unless
circumstances beyond the control of the Operator prevent this.

**Part E | Liability**

**23. LIABILITY OF THE OPERATOR**

23.1 The Operator remains liable for damage caused by its own wilful
misconduct or gross negligence, and for damage arising from death or
personal injury. Nothing in these Terms excludes or limits that
liability.

23.2 Subject to clause 23.1, and to the fullest extent permitted by law,
the Operator is not liable for:

> • any loss arising from a transaction, agreement or dealing between
> users, whether concluded on the Platform or elsewhere;
>
> • the failure of any user to perform what that user promised;
>
> • any breach by a user of the Confidentiality Agreement in clause 9,
> or of any other agreement between users;
>
> • the appropriation, imitation or exploitation by any person of an
> idea or work published on the Platform;
>
> • loss of patentability, of confidentiality or of trade secret
> protection, however it arises;
>
> • any dispute concerning intellectual property or ownership, including
> the question whether any right was validly transferred;
>
> • fraud, misrepresentation, fictitious listings or bad faith on the
> part of any user;
>
> • content published by users, and content reached through a link;
>
> • interruption, error or unavailability of the Platform;
>
> • loss of profit, loss of opportunity, loss of data, or other indirect
> or consequential loss.

23.3 Where a user is a consumer within the meaning of Article 1a of Law
2251/1994, this clause and clause 24 apply only so far as the mandatory
provisions protecting that user allow.

**24. LIMIT OF LIABILITY**

24.1 Subject to clause 23.1, the total liability of the Operator to any
user, for all claims taken together, is limited to five hundred euros
(EUR 500).

24.2 The Operator receives no payment from users and derives no income
from the Platform. This limit reflects that, and reflects the fact that
the Operator neither selects nor verifies what users publish.

**25. INDEMNITY**

25.1 A user who breaches these Terms or infringes the rights of a third
party will indemnify the Operator against any claim, loss, liability or
expense, including reasonable legal costs, that the Operator incurs as a
result. This clause applies to the fullest extent permitted by law and
does not affect the mandatory rights of a user who is a consumer.

25.2 The Operator will notify the user of any such claim without undue
delay and will not settle it without first consulting that user.

**Part F | Duration, records and general provisions**

**26. CLOSING YOUR ACCOUNT, AND WHAT IS KEPT**

26.1 You may close your account at any time.

26.2 When you do, your name, email address, biography, organisation,
location and profile image are permanently replaced with a generic
marker, and your listings are set to inactive so that no further request
for access, acceptance of a Confidentiality Agreement or offer can be
made on them. A listing belonging to a closed account can no longer be
negotiated or acquired, and the Platform says so on the listing.

26.3 The Platform retains the record of Confidentiality Agreements
accepted, offers made and answered, exchanges recorded, reviews given
and received, reports submitted and decided, and the sequence of persons
who have held an idea. Those records are stripped of your identifying
details, save that the name recorded on a Confidentiality Agreement is
kept. Without it the obligation of confidence could not be enforced by
or against you, and the record would be worthless to the very person it
exists to protect.

26.4 Those records are retained because they belong to the other users
as much as to you. A person who accepted a confidentiality obligation
towards you remains bound by it. A person who acquired something from
you needs to be able to show it. A person with an unresolved complaint
against you is entitled to have it examined. Retention on these grounds
is permitted by Article 17(3)(e) of the General Data Protection
Regulation, which excludes the right to erasure so far as processing is
necessary for the establishment, exercise or defence of legal claims.
The Privacy Policy sets out the periods.

26.5 A confidentiality obligation accepted under clause 9 survives the
closure of either account. Access to a private part which was validly
granted before closure remains valid, because it was granted by the
account holder at a time when that person was able to grant it.

26.6 Clauses 6 to 12, 17, 23 to 26 and 28 to 31 continue to apply after
closure.

**27. AMENDMENTS TO THESE TERMS**

27.1 The Operator may amend these Terms.

27.2 Registered users will be notified by email at least thirty days
before an amendment takes effect. The notice will state what has
changed.

27.3 A user who does not accept an amendment may close the account
before the amendment takes effect, at no cost.

27.4 Where an amendment materially alters the rights or obligations of
users, the Operator will ask for renewed express acceptance at the next
login, and the amendment will not bind a user who has not given it.

**28. RIGHTS IN THE PLATFORM ITSELF**

28.1 The name Chiron, the logo, the design, the source code and the
structure of the Platform belong to the Operator or to those who license
them to the Operator, and may not be reproduced or used without written
permission.

**29. GOVERNING LAW AND JURISDICTION**

29.1 These Terms are governed by Greek law.

29.2 The courts of Athens have jurisdiction over any dispute arising out
of these Terms or out of the use of the Platform.

29.3 Clause 29.2 does not deprive a user who is a consumer of the
protection afforded by the mandatory rules of the country in which that
user is habitually resident (Article 6 of Regulation (EC) No 593/2008),
nor of the rights of that user as to jurisdiction under Articles 17 to
19 of Regulation (EU) No 1215/2012.

**30. CONSUMER RIGHTS BETWEEN USERS**

30.1 The Operator sells nothing to you and provides no paid service.
Rights of withdrawal from a distance contract, and the other protections
of Law 2251/1994, which transposes Directive 2011/83/EU on consumer
rights, do not arise in your relationship with the Operator, because
there is no such contract.

30.2 They may arise in a dealing between users. A user who acts in the
course of a trade, business or profession and deals with a user who does
not is a supplier dealing with a consumer, and owes that consumer the
obligations the law imposes, including as to information, withdrawal and
conformity. That is the responsibility of the user concerned. The
Operator neither assesses which users are in that position nor enforces
those obligations.

30.3 Nothing in these Terms restricts a right which the law gives a
consumer and does not permit to be excluded.

**31. GENERAL PROVISIONS**

31.1 If any provision of these Terms is held invalid, the remaining
provisions continue in force, and the invalid provision is replaced by a
valid one approaching its purpose as closely as possible.

31.2 A failure by the Operator to enforce a provision is not a waiver of
it.

31.3 These Terms, together with the Privacy Policy and the Cookie
Policy, constitute the entire agreement between you and the Operator
regarding the Platform. On any question concerning the processing of
personal data, the Privacy Policy prevails.

31.4 The English text of these Terms is the authoritative version. Any
translation is provided for convenience only.

**32. CONTACT**

Evangelos A. Koumasopoulos

80 Panormou Street, 11523, Athens, Greece

legal@chironevo.com

www.chironevo.com
`

export default function Terms() {
  return <LegalDocument title="Terms of Use" content={TERMS_CONTENT} />
}
